// Re-export unified function declaration types from genai_client
pub use genai_client::{FunctionDeclaration, FunctionDeclarationBuilder, FunctionParameters, Tool};

// Re-export Interactions API types for convenient access
pub use genai_client::{
    CodeExecutionLanguage, CodeExecutionOutcome, ContentSummary, CreateInteractionRequest,
    FunctionCallInfo, FunctionResultInfo, GenerationConfig, GroundingChunk, GroundingMetadata,
    InteractionContent, InteractionInput, InteractionResponse, InteractionStatus, StreamChunk,
    ThinkingLevel, UrlContextMetadata, UrlMetadataEntry, UrlRetrievalStatus, UsageMetadata,
    WebSource,
};

// Re-export error type from genai_client
pub use genai_client::GenaiError;

// Interactions API helper functions
//
// ## Export Strategy
//
// We re-export helper functions that users need to **construct** content to send to the API:
// - Multimodal inputs (images, audio, video) - users build these to send
// - Function results - users send these after executing functions
// - Function calls - needed for multi-turn conversations to echo back the model's call
//
// We do NOT re-export helpers for built-in tool outputs (google_search_*, code_execution_*,
// url_context_*) because those are **generated by the model** and users just read them from
// responses via helper methods like `response.google_search_results()`.
// These are still accessible via `rust_genai::interactions_api::*` if needed.
pub mod interactions_api;
pub use interactions_api::{
    audio_data_content, audio_uri_content, build_interaction_input, document_data_content,
    document_uri_content, function_call_content, function_call_content_with_signature,
    function_result_content, image_data_content, image_uri_content, text_content, text_input,
    thought_content, video_data_content, video_uri_content,
};

pub mod client;
pub use client::{Client, ClientBuilder};

pub mod request_builder;
pub use request_builder::{DEFAULT_MAX_FUNCTION_CALL_LOOPS, InteractionBuilder};

pub mod function_calling;
// Re-export public types from function_calling module
pub use function_calling::{CallableFunction, FunctionError};
